; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	E:\C ++\C++Projects\DevTest\snack\main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_b$ = -8						; size = 4
_a$ = -4						; size = 4
_main	PROC
; File e:\c ++\c++projects\devtest\snack\main.cpp
; Line 1
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 2
	mov	DWORD PTR _a$[ebp], 10			; 0000000aH
; Line 4
	mov	eax, DWORD PTR _a$[ebp]
	mov	DWORD PTR _b$[ebp], eax
; Line 5
	xor	eax, eax
; Line 6
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
